name: Datastructure
version: 1.0
main: com.plugin.orderplugin.OrderPlugin
api-version: 1.13

commands:
  setplayer :
    description: 역할 설정
    usage: /setplayer
  상점:
    description: 상점 플러그인
    usage: /상점
  주문:
    description: 주문 플러그인
    usage: /주문